# Generated by Django 4.2.1 on 2023-05-22 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('kategoria_id', models.AutoField(primary_key=True, serialize=False)),
                ('kategoria_type', models.CharField(blank=True, max_length=50, null=True)),
                ('kategoria_img', models.ImageField(upload_to='shop/')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('shop_id', models.AutoField(primary_key=True, serialize=False)),
                ('shop_color', models.CharField(blank=True, max_length=50, null=True)),
                ('shop_name', models.TextField(blank=True, max_length=500, null=True)),
                ('shop_img', models.ImageField(upload_to='shop/')),
                ('shop_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Aplikacioni.kategoria')),
            ],
        ),
    ]
