# Generated by Django 4.2.1 on 2023-05-22 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplikacioni', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kategoria',
            name='kategoria_img',
        ),
    ]
