# Generated by Django 4.2.1 on 2023-05-22 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplikacioni', '0002_remove_kategoria_kategoria_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='shop_price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='shop_review',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
