# Generated by Django 4.2.1 on 2023-05-22 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplikacioni', '0003_shop_shop_price_shop_shop_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='shop_img',
            field=models.ImageField(upload_to='food/'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
