# Generated by Django 4.2.1 on 2023-05-24 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplikacioni', '0007_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
